# Site settings
title: "VetSRev"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://vetsrev.mikegardner.me.uk" # the base hostname & protocol for your site
port: 			  4123

# Build settings
#markdown: kramdown
exclude:
  - README.md
  - _create

keep_files: [bibliography]

# https://github.com/inukshuk/jekyll-scholar
plugins: ['jekyll/scholar']

scholar:
  source: ./_bibliography
  style: ./_bibliography/apakeywords.csl
  bibliography: vetsrev.bib
  #bibliography: vetsrevdemo.bib
  #bibliography: vetsrevtest.bib
  #bibliography: hgf.bib
  #sort_by: year,author
  #order: descending,ascending
  sort_by: author
  order: ascending
  bibliography_list_tag: ul
  details_link: <i>View</i>
